id: AC4FD6192
title: A Prayer to Kindle the Three Faiths, Addressed to the Seventeen Great Paṇḍitas
  of Glorious Nālandā
type: translation
pechas:
- I2C555EC6
- I62AB0239
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:53.354091
  last_modified_at: 2023-01-04 11:52:53.354101
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I2C555EC6/C145: 19F4
  I62AB0239/2100: 19F4
